name = "InfixFunctions"
uuid = "b31481f9-4ab5-4bdc-91b7-486980f94e96"
authors = ["Ismael Venegas Castelló <ismael.vc1337@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]